grafana:
  enabled: true

  adminUser: admin
  adminPassword: ChangeMe@123

  persistence:
    enabled: true
    storageClassName: standard-rwo
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi


alertmanager:
  config:
    global:
      smtp_smarthost: smtp.gmail.com:587
      smtp_from: learndevops694@gmail.com
      smtp_auth_username: learndevops694@gmail.com
      smtp_auth_password: ufps ctcl ngmx nmxe
      smtp_require_tls: true

    route:
      receiver: email-notifications
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

      routes:
        - receiver: "null"
          matchers:
            - alertname="Watchdog"

    receivers:
      - name: email-notifications
        email_configs:
          - to: learndevops694@gmail.com
            send_resolved: true

      - name: "null"

    inhibit_rules: []
