replicaCount: 1

image:
  repository: us-central1-docker.pkg.dev/proserv-task02/springboot-repo/hello-gke
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx

  host: app.devopswithsachin.in

  path: /
  pathType: Prefix

  clusterIssuer: letsencrypt-prod

  tls:
    enabled: true
    secretName: hello-gke-tls
serviceMonitor:
  enabled: true
  interval: 15s
  path: /actuator/prometheus
