spring.application.name=hello-gke

# Expose Actuator endpoints
management.endpoints.web.exposure.include=health,info,prometheus

# Enable Prometheus endpoint
management.endpoint.prometheus.enabled=true

# Enable Prometheus metrics export
management.prometheus.metrics.export.enabled=true

# Show health details
management.endpoint.health.show-details=always

# Add application name as a metric tag
management.metrics.tags.application=hello-gke
