groups:
- name: hello-gke

  rules:

  - alert: HelloGKEDeploymentUnavailable

    expr:
      kube_deployment_status_replicas_available{
        deployment="hello-gke",
        namespace="default"
      } == 0

    for: 2m

    labels:
      severity: critical

    annotations:

      summary:
        Hello GKE deployment unavailable

      description:
        Hello GKE has no available replicas
