grafana:
  enabled: true

  adminUser: admin
  adminPassword: ChangeMe@123

  persistence:
    enabled: true
    storageClassName: standard-rwo
    size: 5Gi

prometheus:
  prometheusSpec:
    retention: 15d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 20Gi

alertmanager:
  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: standard-rwo
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 5Gi
