name: Build Scan Deploy

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  id-token: write

env:
  PROJECT_ID: proserv-task02
  REGION: us-central1
  REPOSITORY: springboot-repo
  IMAGE: hello-gke

jobs:
  deploy:
    runs-on: self-hosted
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
          workload_identity_provider: "projects/153524623211/locations/global/workloadIdentityPools/github-action/providers/github-action"
          service_account: "github-gke-deployer@proserv-task02.iam.gserviceaccount.com"
    
    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2
      with:
        install_components: gke-gcloud-auth-plugin

    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v2
      with:
          cluster_name: "my-tf-cluster"
          location: "us-central1-a"
    
    - name: Verify Environment
      run: |
        kubectl get nodes
        gcloud auth list
    
    - name: Run Unit Tests + Generate Coverage
      run: |
        chmod +x mvnw
        ./mvnw clean test

    - name: Upload Coverage Report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: |
          target/site/jacoco

    - name: Build Application
      run: |
        chmod +x mvnw
        ./mvnw clean package -DskipTests

    - name: Configure Docker
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build Image
      run: |
        docker build \
        -t us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${{ github.sha }} .

    - name: Push Image
      run: |
        docker push \
        us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${{ github.sha }}
        
    - name: Wait for Vulnerability Scan
      run: |
        echo "Waiting 60 seconds..."
        sleep 60

    - name: Generate Vulnerability Report
      run: |
        IMAGE_PATH="us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${{ github.sha }}"
    
        gcloud artifacts docker images describe \
          $IMAGE_PATH \
          --show-package-vulnerability \
          > vulnerability-report.txt
    
    - name: Upload Scan Report
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-report
        path: vulnerability-report.txt
    
    - name: Enforce Security Policy
      run: |
    
        if grep -q "CRITICAL:" vulnerability-report.txt; then
          echo "Deployment blocked (CRITICAL)"
          exit 1
        fi
    
        if grep -q "HIGH:" vulnerability-report.txt; then
          echo "Deployment blocked (HIGH)"
          exit 1
        fi
    
        echo "Scan passed"
              
    - name: Update Deployment
      run: |
        sed -i "s|IMAGE_PLACEHOLDER|us-central1-docker.pkg.dev/${PROJECT_ID}/${REPOSITORY}/${IMAGE}:${{ github.sha }}|g" k8s/deployment.yaml

    - name: Deploy
      run: |
        kubectl apply -f k8s/

    - name: Wait Rollout
      run: |
        kubectl rollout status deployment/hello-gke

    - name: Functional Test

      run: |

        docker run \
         -v ${{ github.workspace }}/tests:/etc/newman \
         postman/newman \
        run /etc/newman/hello-gke-functional.postman_collection.json \
        --env-var baseUrl=http://8.232.82.128

    - name: Verify
      run: |
        kubectl get pods
        kubectl get svc
